name=ESPSmartDash
version=1.1.0
author=Manish KD
maintainer=Manish KD <dmanishkumar093@gmail.com>
sentence=Automatic Web Dashboard for ESP32 and ESP8266
paragraph=Create IoT dashboards with toggles, sliders and sensor gauges using a lightweight web interface.
category=Communication
url=https://github.com/ManishKDtm/ESPSmartDash
architectures=esp8266,esp32
